services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: password-manager
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      TZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists database data

volumes:
  postgres_data: